spring:
  application:
    name: catalog-tools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/catalog_db?currentSchema=catalog_sh&stringtype=unspecified
    username: ucatalog
    password: qmos2wez
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB

server:
  port: 9005
  servlet:
    context-path: /catalog


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui.html


# springdoc:
#   swagger-ui:
#     config-url: /catalog/v3/api-docs/swagger-config
#     url: /catalog/v3/api-docs

    # path: /ui.html
    # config-url: localhost:9005/catalog/api-docs/swagger-config
    # disable-swagger-default-url: true
    # url: /catalog/v3/api-docs
  # api-docs:
  #   path: /api-docs

logging.level.com.alex.catalog: DEBUG

